services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      FASTIFY_ADDRESS: 0.0.0.0
    command: make dev
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app
